name: Test Shell Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  id-token: write  # Required for OIDC AWS Auth
  contents: read   # Required to read repository code



jobs:
    shell-test:
        name: Test Shell Script
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Configure AWS Credentials (OIDC)
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ secrets.ARN_TO_ASSUME }}
              role-session-name: GitHub_to_AWS_via_FederatedOIDC
              aws-region: ${{ secrets.AWS_REGION }}

          - name: Configure SSH
            run: |
                mkdir -p ~/.ssh
                chmod 700 ~/.ssh

                echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

                ssh-keyscan -H ${{ secrets.EC2_USER }} >> ~/.ssh/known_hosts
                chmod 644 ~/.ssh/known_hosts